### ISSUE TITLE
Index a vector_s with a long

### ISSUE THREAD

**Issue by pemsley** [Peteysoft/libmsci#1]
Using clang Apple LLVM version 6.1.0 (clang-602.0.49) 

> kselect.cc:399:5: error: use of overloaded operator '[]' is ambiguous (with operand types 
> 'vector_s<float>' and 'long')
>    (*data)[this->ncur]=val;
>    ^~~~~~~ ~~~~~~~~~~

You need to provide a means to index a vector_s with a long (which is not an int).

`type & operator [] (long ind);`

(and likewise for vector_e.)

P.

**Comment by Peteysoft** [comment]
I am closing these issues with the caveat that at the moment my compiler (g++) does not report these issues so hopefully I have made the right changes. In the future I also hope to get access to an Apple computer.

**Comment by pemsley** [comment]
On 10 October 2015 at 03:35, Peter Mills notifications@github.com wrote:

> I am closing these issues with the caveat that at the moment my compiler
> (g++) does not report these issues so hopefully I have made the right
> changes. In the future I also hope to get access to an Apple computer.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Peteysoft/libmsci/issues/1#issuecomment-147024216.

Fine by me,

If you want clang (it's a decent compiler), not imited to Apple, you can
get it here:

http://clang.llvm.org/get_started.html

Paul
