### ISSUE TITLE
default argument references parameter 'solver'

### ISSUE THREAD

**Issue by pemsley** [Peteysoft/libmsci#2]
The function argument name should not overlap with the default argument:

In file included from constrained.cc:9:
./constrained.h:73:25: error: default argument references parameter 'solver'
                                     gsl_vector *)=&solver);
                                                   ~^~~~~~

Instead of:

```
  int constrained(gsl_matrix *a,    //matrix to solve
        gsl_vector *b,      //solution vector
        gsl_matrix *v,      //constraint normals
        gsl_vector *c,      //constraint thresholds
        gsl_vector *x,      //result
        int (* solver) (gsl_matrix *,
                     gsl_vector *,
                     gsl_vector *)=&solver);
```

use 

```
  int constrained(gsl_matrix *a,    //matrix to solve
        gsl_vector *b,      //solution vector
        gsl_matrix *v,      //constraint normals
        gsl_vector *c,      //constraint thresholds
        gsl_vector *x,      //result
        int (* solver_func) (gsl_matrix *,
                     gsl_vector *,
                     gsl_vector *)=&solver);
```

For `find_interior()` also.

**Comment by Peteysoft** [comment]
Dear Paul:Thanks for the heads up on the errors. I have fixed them and the changes have been committed.Regards,Peter

-------- Original Message --------
Subject: [libmsci] default argument references parameter 'solver' (#2)
