### ISSUE TITLE
a little mistake in the QUICKSTART file

### ISSUE THREAD

**Issue by shekmun** [Peteysoft/libmsci#3]
line 58: fwrite(&D, sizeof(long), 1, fs);
As you said, the vector file have a four byte header, but here it is "sizeof(long)" which is 8 on a x64 system. So I think "sizeof(int)" might be better :).

Thanks!

**Comment by shekmun** [comment]
Oh, it's the QUICKSTART file of the libagf.

**Comment by Peteysoft** [comment]
The QUICKSTART file has been updated. Thanks for the input!
